In [72]:
import numpy as np

### Calculo da Mediana

#### Se o número for ímpar

In [73]:
array_impar = np.arange(8, 1, -1)
array_impar

array([8, 7, 6, 5, 4, 3, 2])

In [74]:
# 1. Coloque os valores de maneira crescente

sorted_number = np.sort(array_impar)

sorted_number

array([2, 3, 4, 5, 6, 7, 8])

In [75]:
# 2. Se for impar, o valor central do len dos números é a mediana

# 2, 3, 4, 5, 6, 7, 8
np.median(sorted_number)

np.float64(5.0)

#### Se o número for par

In [76]:
array_par = np.arange(17, 1, -1)

array_par

array([17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [77]:
# 1. Coloque os valores de maneira crescente

sorted_number = np.sort(array_par)

sorted_number

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [78]:
len(sorted_number)

16

In [79]:
(10 + 9) / 2

9.5

In [80]:
# 2. Se for par, os dois valores centrais somados / 2 é a média

#[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

# Valores centrais: (10 + 9) / 2


np.median(sorted_number)

np.float64(9.5)