# Generated by ChatGPT

https://chatgpt.com/share/681d2712-ddb8-8007-91e5-61db992e188e

##### 🧪 Exercício 1: Elementos maiores que 10

Crie um array 1D com os valores [5, 10, 15, 20, 25] e retorne um novo array contendo apenas os valores maiores que 10.

In [268]:
import numpy as np

In [269]:
array_1d = np.arange(5, 26, 5)
array_filtered = array_1d[array_1d > 10]


array_filtered

array([15, 20, 25])

##### 🧪 Exercício 2: Igualdade entre arrays

Crie dois arrays com 5 números aleatórios entre 1 e 10. Verifique quais posições possuem valores iguais nos dois arrays.

🔎 Dica: Use == para comparar arrays elemento a elemento. Depois, pode usar np.where() para achar os índices.

In [270]:
np.random.seed(4)

arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

arr1 == arr2

array([False, False, False, False,  True])

In [271]:
np.where(arr1 == arr2)

(array([4]),)

##### 🧪 Exercício 3: Filtro com múltiplas condições

Crie um array de 20 números inteiros entre 1 e 100. Filtre os elementos que são pares e maiores que 50.

🔎 Dica: Combine condições com & e use () ao redor de cada uma. Exemplo: (arr % 2 == 0) & (arr > 50)
👉 Boolean indexing – Docs

In [272]:
np.random.seed(4)

arr = np.random.randint(101, size=100)
arr

array([ 46,  55,  69,   1,  87,  72,  50,   9,  58,  94,  55,  55,  57,
        36,  50,  44,  38,  52,   3,   0,  55,  21,  21,  73,  38,  56,
        66,  46,  30,   8,  49,  66,  58,  87,  32,  40,  42,  45,  33,
        32,  28,   3,  79,  98,  95,  57,  50,  17,  81,  89,  73,  59,
        48,  76,  23,  94,  22,  67,  62,  62,  75,  23,  56,  70,  71,
        73,  82,  55,  53,  85,  94,  79,  36,  91,  59,  51,   8,  37,
        72,  59,  54,  96,  30,   4,  54,  75,   8, 100,  31,  40,  17,
        78,   9,  53,  68,  62,  59,   3,   4,  39])

In [273]:
condition = (arr > 50) & (arr % 2 == 0)
filtered_arr = arr[condition]
filtered_arr

array([ 72,  58,  94,  52,  56,  66,  66,  58,  98,  76,  94,  62,  62,
        56,  70,  82,  94,  72,  54,  96,  54, 100,  78,  68,  62])

In [274]:
np.sort(filtered_arr)

array([ 52,  54,  54,  56,  56,  58,  58,  62,  62,  62,  66,  66,  68,
        70,  72,  72,  76,  78,  82,  94,  94,  94,  96,  98, 100])

In [275]:
len(filtered_arr)

25

In [276]:
np.unique(filtered_arr)

array([ 52,  54,  56,  58,  62,  66,  68,  70,  72,  76,  78,  82,  94,
        96,  98, 100])

##### 🧪 Exercício 4: Comparando médias

Crie dois arrays com 10 valores aleatórios entre 0 e 1. Verifique qual array tem a média maior.

🔎 Dica: Use np.mean() para calcular médias e > para comparar.
👉 np.mean – Docs

In [277]:
arr = np.random.rand(10)
arr2 = np.random.rand(10)

media_arr1 = np.mean(arr)
media_arr2 = np.mean(arr2)

greater_median = media_arr1 > media_arr2

msg = f'A média 1 é {"maior" if greater_median else "menor"} que a média dois.\nMédia N1: {media_arr1} \nMédia N2: {media_arr2}'
print(msg)


A média 1 é maior que a média dois.
Média N1: 0.48737548081966925 
Média N2: 0.46475355437464383


##### 🧪 Exercício 5: Quantos valores estão dentro de um intervalo

Dado um array de 15 valores entre 0 e 100, conte quantos valores estão entre 30 e 60, inclusive.

🔎 Dica: Combine condições com &, e depois use np.sum() para contar True.

In [278]:
np.random.seed(15)

arr = np.random.randint(100, size=15)

arr

array([72, 12,  5,  0, 28, 27, 71, 75, 85, 47, 93, 17, 31, 23, 32])

In [279]:
condition = (arr >= 30) & (arr <= 60)
sum_between = np.sum(condition)
values_between = arr[condition]

print(f"Number of values between 30 and 60: {sum_between}")
print("Values between 30 and 60:", values_between)

Number of values between 30 and 60: 3
Values between 30 and 60: [47 31 32]


##### 🧪 Exercício 6: Comparando matrizes

Crie duas matrizes 3x3 de inteiros entre 1 e 9. Verifique se elas são exatamente iguais.

🔎 Dica: Use np.array_equal() para verificar igualdade total entre arrays.
👉 np.array_equal – Docs

In [280]:
arr = np.random.randint(9, size=(2,3,3))

arr

array([[[4, 7, 5],
        [3, 6, 8],
        [2, 1, 1]],

       [[0, 5, 2],
        [2, 1, 8],
        [5, 6, 2]]])

In [281]:
arr[0], arr[1]

(array([[4, 7, 5],
        [3, 6, 8],
        [2, 1, 1]]),
 array([[0, 5, 2],
        [2, 1, 8],
        [5, 6, 2]]))

In [282]:
np.array_equal(arr[0], arr[1])

False

In [285]:
arr1 = np.array([1, 3, 6])
arr2 = np.array([1, 3, 6])

np.array_equal(arr1, arr2)


True

##### 🧪 Exercício 7: Substituindo valores com base em uma condição

Dado um array de inteiros de 1 a 10, substitua os valores ímpares por -1.

🔎 Dica: Use indexação booleana para alterar apenas os valores onde (arr % 2 != 0).
👉 Fancy indexing – Docs

In [284]:
arr = np.arange(11)
impar_values = (arr % 2 != 0)

arr[impar_values] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])