# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [186]:
# Import NumPy as its abbreviation 'np'
import numpy as np
from faker import Faker

faker = Faker('pt-BR')

In [187]:
# Create a 1-dimensional NumPy array using np.array()
array_1d = np.array([faker.first_name() for _ in range(10)])

# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([
  [10, 30, 60],
  [20, 40, 60]
])

# Create a 3-dimensional Numpy array using np.array()
array_3d = np.array([
  [faker.port_number() for _ in range(5)],
  [faker.port_number() for _ in range(5)],
  [faker.port_number() for _ in range(5)]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [188]:
# Atributos do array unidimensional (1D) - (forma, número de dimensões, tipo de dados, tamanho e tipo)

# Forma - Mostra as dimensões do array como uma tupla
print(f"Forma do array: {array_1d.shape}")

# Número de dimensões - Mostra quantos eixos/dimensões o array possui
print(f"Número de dimensões: {array_1d.ndim}")

# Tipo de dados - Mostra o tipo de elementos armazenados no array
print(f"Tipo de dados: {array_1d.dtype}")

# Tamanho - Mostra o número total de elementos no array
print(f"Tamanho: {array_1d.size}")

# Tipo - Mostra o tipo do objeto array
print(f"Tipo: {type(array_1d)}")

Forma do array: (10,)
Número de dimensões: 1
Tipo de dados: <U11
Tamanho: 10
Tipo: <class 'numpy.ndarray'>


In [189]:
# Atributos do array bidimensional (2D) - (forma, número de dimensões, tipo de dados, tamanho e tipo)

# Forma - Retorna uma tupla com as dimensões do array
print(f"Forma do array: {array_2d.shape}")

# Número de dimensões - Retorna o número de eixos/dimensões do array
print(f"Número de dimensões: {array_2d.ndim}")

# Tipo de dados - Retorna o tipo dos elementos armazenados no array
print(f"Tipo de dados: {array_2d.dtype}")

# Tamanho - Retorna o número total de elementos no array
print(f"Tamanho: {array_2d.size}")

# Tipo - Retorna o tipo do objeto array
print(f"Tipo: {type(array_2d)}")

Forma do array: (2, 3)
Número de dimensões: 2
Tipo de dados: int64
Tamanho: 6
Tipo: <class 'numpy.ndarray'>


In [239]:
# Atributos do array tridimensional (3D) - (forma, número de dimensões, tipo de dados, tamanho e tipo)

# Forma - Retorna uma tupla com as dimensões do array
print(f"Forma do array: {array_3d.shape}")

# Número de dimensões - Retorna o número de eixos/dimensões do array
print(f"Número de dimensões: {array_3d.ndim}")

# Tipo de dados - Retorna o tipo dos elementos armazenados no array
print(f"Tipo de dados: {array_3d.dtype}")

# Tamanho - Retorna o número total de elementos no array
print(f"Tamanho: {array_3d.size}")

# Tipo - Retorna o tipo do objeto array
print(f"Tipo: {type(array_3d)}")


Forma do array: (3, 5)
Número de dimensões: 2
Tipo de dados: int64
Tamanho: 15
Tipo: <class 'numpy.ndarray'>


In [191]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

# Como o array 1D so tem uma dimensão, ele será uma coluna dentro do Dataframe
df_1d = pd.DataFrame({
  "names": array_1d
})

df_1d

names
0         Isis
1       Felipe
2      Cecília
3       Pietra
4      Lavínia
5     Caroline
6  Maria Julia
7         Lara
8         Caio
9       Miguel

In [192]:
array_2d

array([[10, 30, 60],
       [20, 40, 60]])

In [193]:

# Como o array_2d é 2d, será criado um DataFrame com linhas e colunas
df_2d = pd.DataFrame(array_2d)
df_2d

0   1   2
0  10  30  60
1  20  40  60

In [194]:
# Como o array_3d é 3d, será criado um DataFrame com linhas e colunas
df_3d = pd.DataFrame(array_3d)
df_3d

0      1      2      3      4
0  26999  35989  21340  33236  63445
1  51913  26266  56473  58211  58836
2  13884  18394  39769  14467  20150

In [195]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2), dtype=np.int8)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [196]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3), dtype=np.int8)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int8)

In [197]:
# Create an array within a range of 0 and 100 with step 3
arr_with_step_three = np.arange(0, 101, 3)

arr_with_step_three

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [198]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_random = np.random.randint(11, size=(7, 2))
arr_random

array([[2, 6],
       [3, 8],
       [2, 4],
       [2, 6],
       [4, 8],
       [6, 1],
       [3, 8]])

In [199]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_floats = np.random.rand(3, 5)
arr_floats

array([[0.96563203, 0.80839735, 0.30461377, 0.09767211, 0.68423303],
       [0.44015249, 0.12203823, 0.49517691, 0.03438852, 0.9093204 ],
       [0.25877998, 0.66252228, 0.31171108, 0.52006802, 0.54671028]])

In [200]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
n = np.random.randint(0, 11, size=(4, 6))

n

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [201]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
r = np.random.randint(1, 11, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(r)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [202]:
r

array([[ 1, 10,  6,  9,  1, 10,  3],
       [ 7,  4,  9,  3,  5,  3,  7],
       [ 5,  9,  7,  2,  4,  9,  2]])

In [203]:
# Find the 0'th index of the latest array you created
r[0]

array([ 1, 10,  6,  9,  1, 10,  3])

In [204]:
# Get the first 2 rows of latest array you created
r[:2]

array([[ 1, 10,  6,  9,  1, 10,  3],
       [ 7,  4,  9,  3,  5,  3,  7]])

In [205]:
# Get the first 2 values of the first 2 rows of the latest array
r[:2, :2]

array([[ 1, 10],
       [ 7,  4]])

In [206]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(42)

r = np.random.randint(11, size=(3, 5))
o = np.ones((3, 5))

In [207]:
r

array([[ 6,  3, 10,  7,  4],
       [ 6,  9,  2,  6, 10],
       [10,  7,  4,  3,  7]])

In [208]:
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [209]:
# Add the two arrays together
add = np.add(r, o)

In [210]:
add

array([[ 7.,  4., 11.,  8.,  5.],
       [ 7., 10.,  3.,  7., 11.],
       [11.,  8.,  5.,  4.,  8.]])

In [211]:
# Create another array of ones of shape (5, 3)
ones = np.ones((3, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [212]:
# Try add the array of ones and the other most recent array together
v = np.add(add, ones)

In [213]:
v

array([[ 8.,  5., 12.,  9.,  6.],
       [ 8., 11.,  4.,  8., 12.],
       [12.,  9.,  6.,  5.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [214]:
# Create another array of ones of shape (3, 5)
sh = np.ones((3, 5))
sh

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [215]:
# Subtract the new array of ones from the other most recent array
np.subtract(v, sh)

array([[ 7.,  4., 11.,  8.,  5.],
       [ 7., 10.,  3.,  7., 11.],
       [11.,  8.,  5.,  4.,  8.]])

In [216]:
print(v)
print('-----')
print(sh)

[[ 8.  5. 12.  9.  6.]
 [ 8. 11.  4.  8. 12.]
 [12.  9.  6.  5.  9.]]
-----
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [217]:
# Multiply the ones array with the latest array
np.multiply(v, sh)

array([[ 8.,  5., 12.,  9.,  6.],
       [ 8., 11.,  4.,  8., 12.],
       [12.,  9.,  6.,  5.,  9.]])

In [218]:
# Take the latest array to the power of 2 using '**'
v ** 2

array([[ 64.,  25., 144.,  81.,  36.],
       [ 64., 121.,  16.,  64., 144.],
       [144.,  81.,  36.,  25.,  81.]])

In [219]:
# Do the same thing with np.square()
np.square(v)

array([[ 64.,  25., 144.,  81.,  36.],
       [ 64., 121.,  16.,  64., 144.],
       [144.,  81.,  36.,  25.,  81.]])

In [220]:
v

array([[ 8.,  5., 12.,  9.,  6.],
       [ 8., 11.,  4.,  8., 12.],
       [12.,  9.,  6.,  5.,  9.]])

In [221]:
# (8 + 5 + 12 + 9 + 6 + 8 + 11 + 4 + 8 + 12 + 12 + 9 + 6 + 5 + 9) / 15

# Find the mean of the latest array using np.mean()
np.mean(v)

np.float64(8.266666666666667)

In [222]:
# Find the maximum of the latest array using np.max()
np.max(v)

np.float64(12.0)

In [223]:
# Find the minimum of the latest array using np.min()
np.min(v)

np.float64(4.0)

In [224]:
# Find the standard deviation of the latest array
np.std(v)

np.float64(2.594010194445829)

In [225]:
# Find the variance of the latest array
np.var(v)

np.float64(6.728888888888888)

In [226]:
# Reshape the latest array to (3, 5, 1)
v.reshape(3, 5, 1)

array([[[ 8.],
        [ 5.],
        [12.],
        [ 9.],
        [ 6.]],

       [[ 8.],
        [11.],
        [ 4.],
        [ 8.],
        [12.]],

       [[12.],
        [ 9.],
        [ 6.],
        [ 5.],
        [ 9.]]])

In [227]:
# Transpose the latest array
v.T

array([[ 8.,  8., 12.],
       [ 5., 11.,  9.],
       [12.,  4.,  6.],
       [ 9.,  8.,  5.],
       [ 6., 12.,  9.]])

What does the transpose do?

In [228]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

r = np.random.randint(10, size=(3, 2))
n = np.random.randint(10, size=(3, 3))

In [229]:
r,n 

(array([[7, 2],
        [5, 4],
        [1, 7]]),
 array([[5, 1, 4],
        [0, 9, 5],
        [8, 0, 9]]))

In [230]:
# Perform a dot product on the two newest arrays you created
r = np.dot(r, n.T)
r

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
s = np.random.randint(10, size=(4, 3))


In [74]:
# Perform a dot product on the two newest arrays you created
r = np.dot(r,s)
r

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [75]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
r = np.dot(r.T, s)
r

array([[14652336, 15653312, 11073272],
       [15893568, 16998193, 12003009],
       [11021440, 11764002,  8333888]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [271]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

np.random.seed(76)

one_arr = np.random.randint(10, size=(5))
two_arr = np.random.randint(10,size=(5))

one_arr, two_arr

(array([8, 9, 3, 8, 8]), array([0, 5, 3, 9, 9]))

In [128]:
# Compare the two arrays with '>'
one_arr > two_arr

array([False,  True, False, False, False])

What happens when you compare the arrays with `>`?

In [129]:
# Compare the two arrays with '>='
two_arr > one_arr

array([False, False, False,  True,  True])

In [224]:
# Find which elements of the first array are greater than 7
one_arr[one_arr > 7]

array([9, 9])

In [270]:
# Which parts of each array are equal? (try using '==')
one_arr == two_arr

array([False, False, False, False, False])

In [454]:
# Sort one of the arrays you just created in ascending order
one_arr, np.sort(one_arr), two_arr, np.sort(two_arr)

(array([8, 9, 3, 8, 8]),
 array([3, 8, 8, 8, 9]),
 array([0, 5, 3, 9, 9]),
 array([0, 3, 5, 9, 9]))

In [456]:
# Sort the indexes of one of the arrays you just created
np.argsort(one_arr), np.argsort(two_arr)

(array([2, 0, 3, 4, 1]), array([0, 2, 1, 3, 4]))

In [458]:
# Find the index with the maximum value in one of the arrays you've created

# Como 9 é o valor máximo do array, o argmax vai trazer o índice que mostra o valor máximo no meu array


one_arr, np.argmax(one_arr)

(array([8, 9, 3, 8, 8]), np.int64(1))

In [459]:
# Find the index with the minimum value in one of the arrays you've created

# Como 0 é o valor minimo do array, o argmax vai trazer o índice que mostra o valor minimo no meu array

two_arr, np.argmin(two_arr)

(array([0, 5, 3, 9, 9]), np.int64(0))

In [185]:

# Cria um gerador com uma seed fixa para resultados reproduzíveis
rng = np.random.default_rng(33)

# Cria uma matriz de inteiros aleatórios entre 0 e 8, com shape (10, 3)
n = rng.integers(0, 9, size=(10, 3))

# Encontra o índice do maior valor em cada linha (axis=1)
max_indices = np.argmax(n, axis=1)

# Mostra os resultados
print("Matriz gerada:\n", n)
print("\nÍndices dos maiores valores em cada linha:\n", max_indices)


Matriz gerada:
 [[7 3 3]
 [5 7 8]
 [2 2 4]
 [5 2 3]
 [8 6 7]
 [4 3 1]
 [6 4 3]
 [2 4 0]
 [0 1 7]
 [3 1 0]]

Índices dos maiores valores em cada linha:
 [0 2 2 0 0 0 0 1 2 0]


In [232]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


rng = np.random.default_rng(33)
n = rng.integers(0, 9, size=(10, 3))

min_indices = np.argmin(n, axis=0)

# Mostra os resultados
print("Matriz gerada:\n", n)
print("\nÍndices dos menores valores em cada linha:\n", min_indices)



Matriz gerada:
 [[7 3 3]
 [5 7 8]
 [2 2 4]
 [5 2 3]
 [8 6 7]
 [4 3 1]
 [6 4 3]
 [2 4 0]
 [0 1 7]
 [3 1 0]]

Índices dos menores valores em cada linha:
 [8 8 7]


In [235]:
# Create an array of normally distributed random numbers
np.random.normal(loc=5, scale=3, size=(3, 3))

array([[0.57101092, 9.46094287, 4.92663447],
       [6.06665395, 6.25103333, 7.49738557],
       [4.11980256, 4.91048429, 5.28537735]])

In [238]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.