In [92]:
import numpy as np

##### Exercício 1 – Transformar um vetor em uma matriz 2D

Tarefa: Transforme esse vetor em uma matriz 2D com 2 linhas e 5 colunas.

In [93]:
vetor = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

vetor.ndim

1

In [94]:
len(vetor)

10

In [95]:
# Internamente vai ser feita uma multiplicação

vetor = vetor.reshape(2,5)

In [96]:
vetor, vetor.ndim

(array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]),
 2)

##### Exercício 2 – Transformar para 3D

Tarefa: Transforme esse vetor em uma matriz 3D com 2 blocos, 2 linhas e 4 colunas.

In [97]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

vetor = vetor.reshape(2, 2, 4)

In [98]:
vetor, vetor.ndim

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]),
 3)

##### Exercício 3 – Achatar uma matriz 2D

Tarefa: Use reshape para "achatar" essa matriz em um vetor 1D.



In [99]:
matriz_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matriz_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
matriz_2d = matriz_2d.reshape(-1)
matriz_2d, matriz_2d.ndim

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), 1)

##### Exercício 4 – Utilizar o -1 para inferir uma dimensão

Tarefa: Use o reshape para transformar esse vetor em uma matriz de 3 linhas e automaticamente calcule o número de colunas utilizando -1.


In [101]:
vetor = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90])

vetor, vetor.ndim

(array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90]),
 1)

In [102]:
vetor = vetor.reshape(3, -1)

vetor, vetor.ndim

(array([[ 5, 10, 15, 20, 25, 30],
        [35, 40, 45, 50, 55, 60],
        [65, 70, 75, 80, 85, 90]]),
 2)

##### 5. Exercício 5 – Erro de reshape


In [103]:
vetor = np.array([10, 20, 30, 40])

vetor, vetor.ndim, vetor.size

(array([10, 20, 30, 40]), 1, 4)

In [104]:
# Isso vai dar erro, pois vetor tem size de 4. 3x3 = 9

# ❌ 9 posições ≠ 4 elementos

vetor = vetor.reshape(3, 3)

vetor

ValueError: cannot reshape array of size 4 into shape (3,3)