In [23]:
import numpy as np

## DataTypes & Attributes

In [24]:
# O tipo de dado principal do numpy é o ndarray

a1 = np.array([1, 2, 3])

a1

array([1, 2, 3])

In [25]:
type(a1)

numpy.ndarray

In [26]:
a2 = np.array([[1., 2., 3.3],
               [4., 5., 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [28]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a1.shape

(3,)

In [30]:
a2.shape

(2, 3)

In [31]:
a3.shape

(2, 3, 3)

In [32]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [33]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [34]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [35]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [38]:
# Criando um dataframe com numpy array

import pandas as pd

df = pd.DataFrame(a2)

df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5